# Override the default values of the info endpoint
info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}
        realm: development

# enable shutdown of application via a POST
endpoints:
    shutdown:
        enabled: true
    health:
        sensitive: false    # display full details for non-authenticated requests

# show the banner file during startup
spring:
    main:
        show_banner: true
    # Redis configuration (see RedisProperties for details)
    redis:
        database: 0 # redis relies on 0-based index database names
        host: redis
        port: 6379

    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
    rabbitmq:
        host: rabbitmq
        port: 5672
#       addresses:
        username: guest
        password: guest
        virtual-host: /
        dynamic: true

# specify the port the service should bind to when using the embedded container, a value of 0 will bind to a randomly selected available port
server:
    port: 8000

# be ready for HTTP proxying
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto

security:
    basic:
        enabled: false

# the context to use for the operation actuators, eg /operations/info
management:
    context-path: /operations
    security:
        enabled: false

# operations shell
shell:
    auth:
        simple:
            user:
                name: operations
                password: operations

# which logback configuration file to use
logging:
    config: classpath:logback.xml

example:
    exchange: monitoring
    mongodbServicePort: 8100
    redisServicePort: 8200
    mySqlServicePort: 8300
    postgreSqlServicePort: 8400
    requireCorrelationId: true

#---------e Profile specific overrides ----------#

# integration testing
---
spring:
    profiles: integration

info:
    app:
        realm: integration-test

# live
---
spring:
    profiles: live

info:
    app:
        realm: production
